/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.acme;

public class Library {
  public boolean someLibraryMethod() {
    return true;
  }

  public void uncovered() {
    System.out.println("I am not covered");
  }
}
